### ISSUE TITLE
Error Building - Prebuilt docker images?

### ISSUE THREAD

**Issue by tpottei1** [GaloisInc/reopt#54]
I am experiencing some build issues. I tried building the master branch and the jhx/new-relinker branch and am build in the Haskell:8.8.3 container. The version of cabal is 3.2.0.0 and ghc is 8.8.3. Would it be possible to make prebuilt docker images with reopt already compiled?

The use case I am researching is making llvm passes for after the binary has been lifted for adding buffer overflow checks and mitigations.

```
Build profile: -w ghc-8.8.3 -O1
In order, the following will be built (use -v for more details):
 - reopt-0.1.0 (lib) (requires build)
 - reopt-0.1.0 (exe:reopt) (requires build)
 - reopt-0.1.0 (exe:reopt-relink) (requires build)
Starting     reopt-0.1.0 (lib)
Building     reopt-0.1.0 (lib)

Failed to build reopt-0.1.0.
Build log (
/root/.cabal/logs/ghc-8.8.3/reopt-0.1.0-3e4a2d216537bdd33630dad51c3af2b33bfedea007fbc380e75e16e76ad84dee.log
):
Configuring library for reopt-0.1.0..
Preprocessing library for reopt-0.1.0..
Building library for reopt-0.1.0..
[ 1 of 18] Compiling Reopt.Analysis.Domains.DiffEquations ( src/Reopt/Analysis/Domains/DiffEquations.hs, dist/build/Reopt/Analysis/Domains/DiffEquations.o )
[ 2 of 18] Compiling Reopt.AnnotatedTypes ( src/Reopt/AnnotatedTypes.hs, dist/build/Reopt/AnnotatedTypes.o )
[ 3 of 18] Compiling Reopt.CFG.FnRep  ( src/Reopt/CFG/FnRep.hs, dist/build/Reopt/CFG/FnRep.o )

src/Reopt/CFG/FnRep.hs:263:25: error:
    * Couldn't match expected type `Doc'
                  with actual type `prettyprinter-1.7.0:Prettyprinter.Internal.Doc
                                      ann1'
      NB: `prettyprinter-1.7.0:Prettyprinter.Internal.Doc'
            is defined in `Prettyprinter.Internal'
                in package `prettyprinter-1.7.0'
          `Doc'
            is defined in `Text.PrettyPrint.ANSI.Leijen.Internal'
                in package `ansi-wl-pprint-0.6.9'
    * In the expression: sexpr "read" [pretty a, pretty tp]
      In a case alternative:
          FnReadMem a tp -> sexpr "read" [pretty a, pretty tp]
      In the expression:
        case rhs of
          FnSetUndefined w -> text "undef ::" <+> brackets (text (show w))
          FnReadMem a tp -> sexpr "read" [pretty a, pretty tp]
          FnCondReadMem _ c a d
            -> sexpr "cond_read" [pretty c, pretty a, ....]
          FnEvalApp a -> ppApp pretty a
          FnEvalArchFn f -> runIdentity (ppArchFn (pure . pretty) f)
    |
263 |       FnReadMem a tp -> sexpr "read" [ pretty a, pretty tp]
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

src/Reopt/CFG/FnRep.hs:263:40: error:
    * Couldn't match expected type `prettyprinter-1.7.0:Prettyprinter.Internal.Doc
                                      ann1'
                  with actual type `Doc'
      NB: `Doc'
            is defined in `Text.PrettyPrint.ANSI.Leijen.Internal'
                in package `ansi-wl-pprint-0.6.9'
          `prettyprinter-1.7.0:Prettyprinter.Internal.Doc'
            is defined in `Prettyprinter.Internal'
                in package `prettyprinter-1.7.0'
    * In the expression: pretty a
      In the second argument of `sexpr', namely `[pretty a, pretty tp]'
      In the expression: sexpr "read" [pretty a, pretty tp]
    |
263 |       FnReadMem a tp -> sexpr "read" [ pretty a, pretty tp]
    |                                        ^^^^^^^^

src/Reopt/CFG/FnRep.hs:263:50: error:
    * Couldn't match expected type `prettyprinter-1.7.0:Prettyprinter.Internal.Doc
                                      ann1'
                  with actual type `Doc'
      NB: `Doc'
            is defined in `Text.PrettyPrint.ANSI.Leijen.Internal'
                in package `ansi-wl-pprint-0.6.9'
          `prettyprinter-1.7.0:Prettyprinter.Internal.Doc'
            is defined in `Prettyprinter.Internal'
                in package `prettyprinter-1.7.0'
    * In the expression: pretty tp
      In the second argument of `sexpr', namely `[pretty a, pretty tp]'
      In the expression: sexpr "read" [pretty a, pretty tp]
    |
263 |       FnReadMem a tp -> sexpr "read" [ pretty a, pretty tp]
    |                                                  ^^^^^^^^^
```

**Comment by joehendrix** [comment]
@tpottei1 I don't know if you are still interested in Reopt, but we now have a prebuilt docker image.  We also make it easy to try out reopt through Gitpod.  See the [latest README](https://github.com/GaloisInc/reopt/blob/master/README.md) for more details.
